# mkdir certs && cd "$_"
# openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj /CN=ais-client
# openssl pkcs12 -export -in cert.pem -inkey key.pem -out ais-client-store.p12 -name "AIS Client Certificate"
# wget -qO - https://github.com/cisagov/FLAREclient-container/releases/latest | docker import - ais-client:05-24-2022

version: '3'
services:
  ais-client:
    image: 'ais-client'
    environment:
      - CERT_ALIAS="ais-client-store.p12"
      - CERT_KEYSTORE_PASS=""
      - CERT_TRUSTSTORE_PASS=""
      - FLARE_CLIENT_SVC_HOST="127.0.0.1"
      - FLARE_CLIENT_SVC_PORT="8083"
      - JAVA_OPTS="-Xmx2g"
      - MAX_REQUEST_SIZE="150M"
      - NGINX_DEBUG_LOG="false"
      - NGINX_PROXY_TIMEOUT="690s"
      - TIMEOUT_API="680000"
      - TIMEOUT_DEFAULT="60000"
      - TIMEOUT_TAXII21_DOWNLOAD="660000"
      - TIMEOUT_TAXII21_MANIFEST="660000"
      - TIMEOUT_TAXII21_UPLOAD="660000"
    volumes:
      - "$PWD/certs/:/opt/app/devKeystore.p12:Z"
    ports:
      - '443:443'
      - '8083:8083'
    networks:
      - ais20
    restart: unless-stopped
  networks:
    - ais20: {}

