---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: flareclient-db
    spec:
      replicas: 1
      selector:
        name: flareclient-db
      strategy:
        type: Rolling
        rollingParams:
      template:
        metadata:
          labels:
            name: flareclient-db
        spec:
          containers:
            - env:
              - name: MONGODB_ADMIN_PASSWORD
                value: 12qwaszx@#WESDXC
              - name: IM_DASHBOARD_UI_SVC_HOST
                value: flareclient-db.${NAMESPACE}.svc
              - name: IM_DASHBOARD_UI_SVC_PORT
                value: "8443"
              imagePullPolicy: Always
              name: flareclient-db
              image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/flareclient-db:${IMAGE_VERSION}
            serviceAccountName: "database-sa"
            imagePullSecrets:
              - name: artifactory-puller
      triggers:
      - type: ConfigChange
parameters:
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
