---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: flareclient-mongo
    spec:
      replicas: 1
      selector:
        name: flareclient-mongo
      strategy:
        type: Rolling
        rollingParams:
      template:
        metadata:
          labels:
            name: flareclient-mongo
        spec:
          containers:
          - env:
            - name: MONGODB_ADMIN_PASSWORD
              value: QWASZX23wesdxc            
            imagePullPolicy: Always
            name: flareclient-mongo
            image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/flareclient-mongo:${IMAGE_VERSION}
          serviceAccountName: "database-sa"
          imagePullSecrets:
            - name: artifactory-puller
      triggers:
      - type: ConfigChange
parameters:
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
