---
apiVersion: v1
kind: Template
metadata:
  name: service-account-template
objects:
  - apiVersion: v1
    kind: SecurityContextConstraints
    metadata:
      name: database-scc
    runAsUser:
      type: MustRunAs
      uid: 999
    seLinuxContext:
      type: MustRunAs
    users:
      - database-sa