---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        external: hr-db
      name: hr-db
    spec:
      ports:
      - nodePort: 0
        port: 3310
        protocol: TCP
        targetPort: 3310
      sessionAffinity: None
      selector:
        name: hr-db
      type: ClusterIP
    status:
      loadBalancer: {}