---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        external: flareclient-db
      name: flareclient-db
    spec:
      ports:
      - nodePort: 0
        port: 27017
        protocol: TCP
        targetPort: 27017
      sessionAffinity: None
      selector:
        name: flareclient-db
      type: ClusterIP
    status:
      loadBalancer: {}