#!/usr/bin/env docker
---

version: '3'
services:
  ais-client:
    image: "${CLIENT_NAME:-ais-client}"
    container_name: "${CLIENT_NAME:-ais-client}"
    privileged: true
    restart: unless-stopped
    # networks:
    #   ais-bridge:
    #     aliases:
    #       - ais-client-bridge
    ports:
      - 8083:8083
      - 443:443
    volumes:
      - ${CERT_PATH?err}:/opt/app/devKeystore.p12:Z
      - ${CERT_PATH?err}:/opt/app/keystore.p12:Z
      # - ${SECRETS_DIR?err}:/opt/app/secrets
    environment:
      # - SECRETS_DIR=/opt/app/secrets
      - CERT_ALIAS=${CERT_ALIAS?err}
      - CERT_KEYSTORE_PASS=${CERT_PASS?err}
      - CERT_TRUSTSTORE_PASS=${CERT_PASS?err}
      - FLARE_CLIENT_SVC_HOST=0.0.0.0
      - FLARE_CLIENT_SVC_PORT=8083
      - JAVA_OPTS=-Xmx2g
      # - JAVA_OPTS=-Dspring.profiles.active
      - MAX_REQUEST_SIZE=150M
      - NGINX_DEBUG_LOG=false
      - NGINX_PROXY_TIMEOUT=690s
      - TIMEOUT_API=680000
      - TIMEOUT_DEFAULT=60000
      - TIMEOUT_TAXII21_DOWNLOAD=660000
      - TIMEOUT_TAXII21_MANIFEST=660000
      - TIMEOUT_TAXII21_UPLOAD=660000

# networks:
#   ais-bridge:
#     driver: bridge
#     # external: true
#     # driver_opts:
#     #   com.docker.network.enable_ipv6: false
