#!/usr/bin/env docker
---

version: '3'
services:
  ais-client:
    image: "${CLIENT_NAME:-ais-client}"
    container_name: "${CLIENT_NAME:-ais-client}"
    restart: unless-stopped
    networks:
      external-bridge:
        aliases:
          - ais-client-bridge
    ports:
      - '443:443'
      - '8083:8083'
    volumes:
      - "${CERT_PATH?err}:/opt/app/devKeystore.p12:Z"
    environment:
      - CERT_ALIAS="ais-client-store.p12"
      - CERT_KEYSTORE_PASS=""
      - CERT_TRUSTSTORE_PASS=""
      - FLARE_CLIENT_SVC_HOST="127.0.0.1"
      - FLARE_CLIENT_SVC_PORT="8083"
      - JAVA_OPTS="-Xmx2g"
      - MAX_REQUEST_SIZE="150M"
      - NGINX_DEBUG_LOG="false"
      - NGINX_PROXY_TIMEOUT="690s"
      - TIMEOUT_API="680000"
      - TIMEOUT_DEFAULT="60000"
      - TIMEOUT_TAXII21_DOWNLOAD="660000"
      - TIMEOUT_TAXII21_MANIFEST="660000"
      - TIMEOUT_TAXII21_UPLOAD="660000"

networks:
  external-bridge:
    driver: bridge
    # external: true
    # driver_opts:
    #   com.docker.network.enable_ipv6: false
